<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>se.mdu</groupId>
  <artifactId>mdu-oss-parent</artifactId>
  <version>70-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>${project.groupId}:${project.artifactId}</name>
  <description>En Maven-parent för MDU-produkter skrivna i Java.</description>
  <url>https://github.com/mdh-se/${project.artifactId}</url>
  <organization>
    <name>Mälardalens universitet</name>
    <url>https://www.mdu.se/</url>
  </organization>
  <licenses>
    <license>
      <name>The MIT License</name>
      <url>https://opensource.org/licenses/MIT</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>Dennis Lundberg</name>
    </developer>
    <developer>
      <name>Johan Nilsson</name>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:https://github.com/mdh-se/${project.artifactId}.git</connection>
    <developerConnection>scm:git:https://github.com/mdh-se/${project.artifactId}.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/mdh-se/${project.artifactId}</url>
  </scm>

  <properties>
    <!-- Plugins och deras dependencies -->
    <mdu.appassembler-maven-plugin.version>2.1.0</mdu.appassembler-maven-plugin.version>
    <mdu.build-helper-maven-plugin.version>3.0.0</mdu.build-helper-maven-plugin.version>
    <mdu.central-publishing-maven-plugin.version>0.10.0</mdu.central-publishing-maven-plugin.version>
    <mdu.checkstyle.version>8.31</mdu.checkstyle.version>
    <mdu.cxf-codegen-plugin.version>3.6.5</mdu.cxf-codegen-plugin.version>
    <mdu.cxf-xjc-plugin.version>3.3.4</mdu.cxf-xjc-plugin.version>
    <mdu.cxf.xjcplugins.version>3.3.4</mdu.cxf.xjcplugins.version>
    <mdu.exec-maven-plugin.version>1.4.0</mdu.exec-maven-plugin.version>
    <mdu.extra-enforcer-rules.version>1.7.0</mdu.extra-enforcer-rules.version>
    <mdu.jacoco-maven-plugin.version>0.8.14</mdu.jacoco-maven-plugin.version>
    <mdu.java.version>17</mdu.java.version>
    <mdu.jaxb-maven-plugin.version>4.0.8</mdu.jaxb-maven-plugin.version>
    <mdu.krasa-jaxb-tools.version>2.2</mdu.krasa-jaxb-tools.version>
    <mdu.maven.version>3.0</mdu.maven.version>
    <mdu.maven-antrun-plugin.version>1.8</mdu.maven-antrun-plugin.version>
    <mdu.maven-assembly-plugin.version>3.1.0</mdu.maven-assembly-plugin.version>
    <mdu.maven-bundle-plugin.version>5.1.9</mdu.maven-bundle-plugin.version>
    <mdu.maven-changes-plugin.templateEncoding>UTF-8</mdu.maven-changes-plugin.templateEncoding>
    <mdu.maven-changes-plugin.version>2.12.1</mdu.maven-changes-plugin.version>
    <mdu.maven-checkstyle-plugin.version>3.1.2</mdu.maven-checkstyle-plugin.version>
    <mdu.maven-clean-plugin.version>3.1.0</mdu.maven-clean-plugin.version>
    <mdu.maven-compiler-plugin.version>3.14.0</mdu.maven-compiler-plugin.version>
    <mdu.maven-dependency-plugin.version>3.6.1</mdu.maven-dependency-plugin.version>
    <mdu.maven-deploy-plugin.version>2.8.2</mdu.maven-deploy-plugin.version>
    <mdu.maven-ear-plugin.version>2.10.1</mdu.maven-ear-plugin.version>
    <mdu.maven-ejb-plugin.version>3.0.0</mdu.maven-ejb-plugin.version>
    <mdu.maven-enforcer-plugin.version>3.4.1</mdu.maven-enforcer-plugin.version>
    <mdu.maven-gpg-plugin.version>1.6</mdu.maven-gpg-plugin.version>
    <mdu.maven-install-plugin.version>2.5.2</mdu.maven-install-plugin.version>
    <mdu.maven-jar-plugin.version>3.2.0</mdu.maven-jar-plugin.version>
    <mdu.maven-javadoc-plugin.version>3.12.0</mdu.maven-javadoc-plugin.version>
    <mdu.maven-jxr-plugin.version>3.1.1</mdu.maven-jxr-plugin.version>
    <mdu.maven-pdf-plugin.version>1.4</mdu.maven-pdf-plugin.version>
    <mdu.maven-plugin-plugin.version>3.5.2</mdu.maven-plugin-plugin.version>
    <!-- Do NOT update this to a newer version until maven-site-plugin is also updated to 3.20.0 -->
    <mdu.maven-pmd-plugin.version>3.24.0</mdu.maven-pmd-plugin.version>
    <mdu.maven-project-info-reports-plugin.version>3.0.0</mdu.maven-project-info-reports-plugin.version>
    <mdu.maven-release-plugin.version>2.5.3</mdu.maven-release-plugin.version>
    <mdu.maven-remote-resources-plugin.version>1.5</mdu.maven-remote-resources-plugin.version>
    <mdu.maven-resources-plugin.version>3.2.0</mdu.maven-resources-plugin.version>
    <mdu.maven-scm-provider-jgit.version>1.9.5</mdu.maven-scm-provider-jgit.version>
    <mdu.maven-site-plugin.version>3.7.1</mdu.maven-site-plugin.version>
    <mdu.maven-source-plugin.version>3.2.1</mdu.maven-source-plugin.version>
    <mdu.maven-surefire-plugin.version>3.5.5</mdu.maven-surefire-plugin.version>
    <mdu.maven-toolchains-plugin.version>1.1</mdu.maven-toolchains-plugin.version>
    <mdu.maven-wagon.version>3.1.0</mdu.maven-wagon.version>
    <mdu.maven-war-plugin.version>3.4.0</mdu.maven-war-plugin.version>
    <mdu.mdu-build-resources.version>34</mdu.mdu-build-resources.version>
    <mdu.sortpom-maven-plugin.version>2.10.0</mdu.sortpom-maven-plugin.version>
    <mdu.spotbugs-maven-plugin.version>4.9.8.2</mdu.spotbugs-maven-plugin.version>
    <mdu.spring-boot-maven-plugin.version>2.7.0</mdu.spring-boot-maven-plugin.version>
    <mdu.sql-maven-plugin.version>1.5</mdu.sql-maven-plugin.version>
    <mdu.tidy-maven-plugin.version>1.1.0</mdu.tidy-maven-plugin.version>
    <mdu.versions-maven-plugin.version>2.21.0</mdu.versions-maven-plugin.version>

    <!-- MDU-specific properties -->
    <mdh.logging.email.buffer>10</mdh.logging.email.buffer>
    <mdh.logging.email.level>off</mdh.logging.email.level>
    <mdh.logging.file.encoding>UTF-8</mdh.logging.file.encoding>
    <mdh.logging.file.level>debug</mdh.logging.file.level>
    <mdh.logging.product.level>debug</mdh.logging.product.level>

    <!-- Standard Maven properties -->
    <maven.compiler.release>${mdu.java.version}</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <project.scm.id>github</project.scm.id>
  </properties>

  <build>
    <resources>
      <resource>
        <filtering>true</filtering>
        <directory>src/main/resources</directory>
      </resource>
    </resources>
    <testResources>
      <testResource>
        <filtering>true</filtering>
        <directory>src/test/resources</directory>
      </testResource>
    </testResources>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.github.ekryd.sortpom</groupId>
          <artifactId>sortpom-maven-plugin</artifactId>
          <version>${mdu.sortpom-maven-plugin.version}</version>
          <configuration>
            <predefinedSortOrder>default_1_0_0</predefinedSortOrder>
            <keepBlankLines>true</keepBlankLines>
            <sortDependencies>groupId,artifactId</sortDependencies>
            <verifyFail>Stop</verifyFail>
          </configuration>
        </plugin>
        <plugin>
          <groupId>com.github.spotbugs</groupId>
          <artifactId>spotbugs-maven-plugin</artifactId>
          <version>${mdu.spotbugs-maven-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.cxf</groupId>
          <artifactId>cxf-codegen-plugin</artifactId>
          <version>${mdu.cxf-codegen-plugin.version}</version>
          <dependencies>
            <!-- Generera JSR-303 Bean Validation Annotations -->
            <dependency>
              <groupId>com.fillumina</groupId>
              <artifactId>krasa-jaxb-tools</artifactId>
              <version>${mdu.krasa-jaxb-tools.version}</version>
            </dependency>
            <!-- Lägg till toString() metoder -->
            <dependency>
              <groupId>org.apache.cxf.xjcplugins</groupId>
              <artifactId>cxf-xjc-ts</artifactId>
              <version>${mdu.cxf.xjcplugins.version}</version>
            </dependency>
          </dependencies>
          <configuration>
            <defaultOptions>
              <!-- Lös automatiskt namnkonflikter utan att behöva använda binding customizations -->
              <autoNameResolution>true</autoNameResolution>
              <bindingFiles>
                <bindingFile>${project.basedir}/src/main/xjb/bindings.xml</bindingFile>
              </bindingFiles>
              <extraargs>
                <!-- Generera JSR-303 Bean Validation Annotations -->
                <extraarg>-xjc-XJsr303Annotations</extraarg>
                <!-- Lägg till toString() metoder -->
                <extraarg>-xjc-Xts:style:org.apache.commons.lang3.builder.ToStringStyle.SHORT_PREFIX_STYLE</extraarg>
              </extraargs>
              <!-- Ta inte med header som innehåller datum - lättare att diffa -->
              <suppressGeneratedDate>true</suppressGeneratedDate>
            </defaultOptions>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.cxf</groupId>
          <artifactId>cxf-xjc-plugin</artifactId>
          <version>${mdu.cxf-xjc-plugin.version}</version>
          <dependencies>
            <!-- Generera JSR-303 Bean Validation Annotations -->
            <dependency>
              <groupId>com.fillumina</groupId>
              <artifactId>krasa-jaxb-tools</artifactId>
              <version>${mdu.krasa-jaxb-tools.version}</version>
            </dependency>
            <!-- Lägg till toString() metoder -->
            <dependency>
              <groupId>org.apache.cxf.xjcplugins</groupId>
              <artifactId>cxf-xjc-ts</artifactId>
              <version>${mdu.cxf.xjcplugins.version}</version>
            </dependency>
          </dependencies>
          <configuration>
            <sourceRoot>${project.build.directory}/generated</sourceRoot>
            <xsdOptions>
              <xsdOption>
                <xsdDir>${project.basedir}/src/main/resources</xsdDir>
                <bindingFile>${project.basedir}/src/main/xjb/bindings.xml</bindingFile>
                <extension>true</extension>
                <extensionArgs>
                  <!-- Ta inte med header som innehåller datum - lättare att diffa -->
                  <extensionArg>-no-header</extensionArg>
                  <!-- JSR-303 Bean Validation Annotations -->
                  <extensionArg>-XJsr303Annotations</extensionArg>
                  <!-- Insert toString() method -->
                  <extensionArg>-Xts:style:org.apache.commons.lang3.builder.ToStringStyle.SHORT_PREFIX_STYLE</extensionArg>
                </extensionArgs>
              </xsdOption>
            </xsdOptions>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.felix</groupId>
          <artifactId>maven-bundle-plugin</artifactId>
          <version>${mdu.maven-bundle-plugin.version}</version>
          <extensions>true</extensions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>${mdu.maven-antrun-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>${mdu.maven-assembly-plugin.version}</version>
          <dependencies>
            <dependency>
              <groupId>se.mdu</groupId>
              <artifactId>mdu-build-resources</artifactId>
              <version>${mdu.mdu-build-resources.version}</version>
            </dependency>
          </dependencies>
          <configuration>
            <tarLongFileMode>gnu</tarLongFileMode>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-changes-plugin</artifactId>
          <version>${mdu.maven-changes-plugin.version}</version>
          <dependencies>
            <dependency>
              <groupId>se.mdu</groupId>
              <artifactId>mdu-build-resources</artifactId>
              <version>${mdu.mdu-build-resources.version}</version>
            </dependency>
          </dependencies>
          <configuration>
            <!-- Inheriting POMs need to specify mailSender, smtpHost and toAddresses -->
            <failOnError>true</failOnError>
            <mailContentType>text/plain; charset=${mdu.maven-changes-plugin.templateEncoding}</mailContentType>
            <runOnlyAtExecutionRoot>true</runOnlyAtExecutionRoot>
            <subject>${project.artifactId}-${project.version} byggd av ${user.name}</subject>
            <templateDirectory>se/mdh/plugins/announcement</templateDirectory>
            <templateEncoding>${mdu.maven-changes-plugin.templateEncoding}</templateEncoding>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-checkstyle-plugin</artifactId>
          <version>${mdu.maven-checkstyle-plugin.version}</version>
          <dependencies>
            <dependency>
              <groupId>com.puppycrawl.tools</groupId>
              <artifactId>checkstyle</artifactId>
              <version>${mdu.checkstyle.version}</version>
            </dependency>
            <dependency>
              <groupId>se.mdu</groupId>
              <artifactId>mdu-build-resources</artifactId>
              <version>${mdu.mdu-build-resources.version}</version>
            </dependency>
          </dependencies>
          <configuration>
            <configLocation>mdh/checkstyle.xml</configLocation>
            <suppressionsLocation>checkstyle-suppressions.xml</suppressionsLocation>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-clean-plugin</artifactId>
          <version>${mdu.maven-clean-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${mdu.maven-compiler-plugin.version}</version>
          <configuration>
            <compilerArgument>-Xlint:all,-serial,-dep-ann</compilerArgument>
            <showDeprecation>true</showDeprecation>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>${mdu.maven-dependency-plugin.version}</version>
          <configuration>
            <ignoreNonCompile>true</ignoreNonCompile>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>${mdu.maven-deploy-plugin.version}</version>
          <configuration>
            <retryFailedDeploymentCount>5</retryFailedDeploymentCount>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-ear-plugin</artifactId>
          <version>${mdu.maven-ear-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-ejb-plugin</artifactId>
          <version>${mdu.maven-ejb-plugin.version}</version>
          <configuration>
            <archive>
              <manifest>
                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
              </manifest>
            </archive>
            <clientExcludes>
              <clientExclude>META-INF/*.xml</clientExclude>
              <clientExclude>**/*Adapter.class</clientExclude>
              <clientExclude>**/*Bean.class</clientExclude>
              <clientExclude>**/*Local.class</clientExclude>
              <clientExclude>**/*LocalHome.class</clientExclude>
              <clientExclude>**/HomeFactory.class</clientExclude>
            </clientExcludes>
            <generateClient>true</generateClient>
            <filterDeploymentDescriptor>true</filterDeploymentDescriptor>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <version>${mdu.maven-enforcer-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-failsafe-plugin</artifactId>
          <version>${mdu.maven-surefire-plugin.version}</version>
          <dependencies>
            <dependency>
              <groupId>org.apache.maven.surefire</groupId>
              <artifactId>surefire-junit47</artifactId>
              <version>${mdu.maven-surefire-plugin.version}</version>
            </dependency>
          </dependencies>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-gpg-plugin</artifactId>
          <version>${mdu.maven-gpg-plugin.version}</version>
          <configuration>
            <!-- Required for GPG 2 -->
            <gpgArguments>
              <arg>--pinentry-mode</arg>
              <arg>loopback</arg>
            </gpgArguments>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-install-plugin</artifactId>
          <version>${mdu.maven-install-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${mdu.maven-jar-plugin.version}</version>
          <configuration>
            <archive>
              <manifest>
                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
              </manifest>
            </archive>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>${mdu.maven-javadoc-plugin.version}</version>
          <configuration>
            <tags>
              <tag>
                <name>todo</name>
                <placement>X</placement>
                <head>To do:</head>
              </tag>
            </tags>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jxr-plugin</artifactId>
          <version>${mdu.maven-jxr-plugin.version}</version>
          <configuration>
            <linkJavadoc>false</linkJavadoc>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-pdf-plugin</artifactId>
          <version>${mdu.maven-pdf-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-plugin-plugin</artifactId>
          <version>${mdu.maven-plugin-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-pmd-plugin</artifactId>
          <version>${mdu.maven-pmd-plugin.version}</version>
          <configuration>
            <rulesets>
              <ruleset>rulesets/maven.xml</ruleset>
            </rulesets>
            <targetJdk>${maven.compiler.release}</targetJdk>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <version>${mdu.maven-release-plugin.version}</version>
          <dependencies>
            <dependency>
              <groupId>org.apache.maven.scm</groupId>
              <artifactId>maven-scm-provider-jgit</artifactId>
              <version>${mdu.maven-scm-provider-jgit.version}</version>
            </dependency>
          </dependencies>
          <configuration>
            <autoVersionSubmodules>true</autoVersionSubmodules>
            <providerImplementations>
              <git>jgit</git>
            </providerImplementations>
            <!-- Aktivera vår egen release-profil vid release -->
            <releaseProfiles>mdh-release</releaseProfiles>
            <!-- Deaktivera default profilen "release-profile" vid release -->
            <useReleaseProfile>false</useReleaseProfile>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-remote-resources-plugin</artifactId>
          <version>${mdu.maven-remote-resources-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>${mdu.maven-resources-plugin.version}</version>
          <configuration>
            <escapeString>\</escapeString>
            <nonFilteredFileExtensions>
              <nonFilteredFileExtension>keystore</nonFilteredFileExtension>
              <nonFilteredFileExtension>pdf</nonFilteredFileExtension>
              <nonFilteredFileExtension>pfx</nonFilteredFileExtension>
            </nonFilteredFileExtensions>
            <propertiesEncoding>ISO-8859-1</propertiesEncoding>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-site-plugin</artifactId>
          <version>${mdu.maven-site-plugin.version}</version>
          <dependencies>
            <!-- Add support for ssh/scp, required by Maven 3 -->
            <dependency>
              <groupId>org.apache.maven.wagon</groupId>
              <artifactId>wagon-ssh</artifactId>
              <version>${mdu.maven-wagon.version}</version>
            </dependency>
          </dependencies>
          <configuration>
            <locales>sv</locales>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-source-plugin</artifactId>
          <version>${mdu.maven-source-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${mdu.maven-surefire-plugin.version}</version>
          <dependencies>
            <dependency>
              <groupId>org.apache.maven.surefire</groupId>
              <artifactId>surefire-junit47</artifactId>
              <version>${mdu.maven-surefire-plugin.version}</version>
            </dependency>
          </dependencies>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-toolchains-plugin</artifactId>
          <version>${mdu.maven-toolchains-plugin.version}</version>
          <configuration>
            <toolchains>
              <jdk>
                <version>${mdu.java.version}</version>
              </jdk>
            </toolchains>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-war-plugin</artifactId>
          <version>${mdu.maven-war-plugin.version}</version>
          <configuration>
            <archive>
              <manifest>
                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
              </manifest>
            </archive>
            <archiveClasses>true</archiveClasses>
            <escapeString>\</escapeString>
            <filteringDeploymentDescriptors>true</filteringDeploymentDescriptors>
            <!-- Förhindra att filer som kopierats till WEB-INF/lib av maven-dependency-plugin raderas -->
            <outdatedCheckPath>NONE</outdatedCheckPath>
            <outputFileNameMapping>@{artifactId}@@{dashClassifier?}@.@{extension}@</outputFileNameMapping>
            <propertiesEncoding>ISO-8859-1</propertiesEncoding>
            <webResources>
              <resource>
                <targetPath>WEB-INF/classes</targetPath>
                <filtering>true</filtering>
                <directory>src/main/webapp/WEB-INF/classes</directory>
              </resource>
            </webResources>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>appassembler-maven-plugin</artifactId>
          <version>${mdu.appassembler-maven-plugin.version}</version>
          <configuration>
            <configurationDirectory>conf</configurationDirectory>
            <configurationSourceDirectory>src/main/config</configurationSourceDirectory>
            <copyConfigurationDirectory>true</copyConfigurationDirectory>
            <escapeString>\</escapeString>
            <filterConfigurationDirectory>true</filterConfigurationDirectory>
            <outputFileNameMapping>@{artifactId}@@{dashClassifier?}@.@{extension}@</outputFileNameMapping>
            <repositoryLayout>flat</repositoryLayout>
            <repositoryName>lib</repositoryName>
            <useWildcardClassPath>true</useWildcardClassPath>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>build-helper-maven-plugin</artifactId>
          <version>${mdu.build-helper-maven-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>exec-maven-plugin</artifactId>
          <version>${mdu.exec-maven-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>sql-maven-plugin</artifactId>
          <version>${mdu.sql-maven-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>tidy-maven-plugin</artifactId>
          <version>${mdu.tidy-maven-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>versions-maven-plugin</artifactId>
          <version>${mdu.versions-maven-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <version>${mdu.jacoco-maven-plugin.version}</version>
          <configuration>
            <outputEncoding>UTF-8</outputEncoding>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.jvnet.jaxb</groupId>
          <artifactId>jaxb-maven-plugin</artifactId>
          <version>${mdu.jaxb-maven-plugin.version}</version>
          <configuration>
            <args>
              <!-- Insert toString() method -->
              <arg>-Xcommons-lang</arg>
              <arg>-Xcommons-lang:ToStringStyle=SHORT_PREFIX_STYLE</arg>
              <!-- Generate JSR-303 Bean Validation Annotations -->
              <arg>-XJsr303Annotations</arg>
              <arg>-XJsr303Annotations:validationAnnotations=jakarta</arg>
            </args>
            <bindingDirectory>src/main/xjb</bindingDirectory>
            <bindingIncludes>
              <include>bindings.xml</include>
            </bindingIncludes>
            <extension>true</extension>
            <noFileHeader>true</noFileHeader>
            <plugins>
              <!-- Generate JSR-303 Bean Validation Annotations -->
              <plugin>
                <groupId>com.fillumina</groupId>
                <artifactId>krasa-jaxb-tools</artifactId>
                <version>${mdu.krasa-jaxb-tools.version}</version>
              </plugin>
              <!-- Insert toString() method -->
              <plugin>
                <groupId>org.jvnet.jaxb</groupId>
                <artifactId>jaxb-plugins</artifactId>
                <version>${mdu.jaxb-maven-plugin.version}</version>
              </plugin>
            </plugins>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.sonatype.central</groupId>
          <artifactId>central-publishing-maven-plugin</artifactId>
          <version>${mdu.central-publishing-maven-plugin.version}</version>
          <extensions>true</extensions>
          <configuration>
            <publishingServerId>central</publishingServerId>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <version>${mdu.spring-boot-maven-plugin.version}</version>
          <configuration>
            <embeddedLaunchScriptProperties>
              <logFolder>$HOME/logs/${project.artifactId}</logFolder>
              <pidFolder>$HOME/pid</pidFolder>
            </embeddedLaunchScriptProperties>
            <executable>true</executable>
            <layout>ZIP</layout>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>com.github.ekryd.sortpom</groupId>
        <artifactId>sortpom-maven-plugin</artifactId>
        <executions>
          <execution>
            <phase>validate</phase>
            <goals>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <executions>
          <execution>
            <id>enforce-banned-dependencies</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <bannedDependencies>
                  <excludes>
                    <exclude>com.sun.mail:javax.mail</exclude>
                  </excludes>
                  <message>Please use javax.mail:mail instead.</message>
                </bannedDependencies>
                <bannedDependencies>
                  <excludes>
                    <exclude>org.slf4j:jcl-over-slf4j</exclude>
                  </excludes>
                  <message>Please use commons-logging:commons-logging and org.apache.logging.log4j:log4j-jcl instead.</message>
                </bannedDependencies>
              </rules>
              <fail>true</fail>
            </configuration>
          </execution>
          <execution>
            <id>enforce-versions</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireJavaVersion>
                  <version>${maven.compiler.release}</version>
                </requireJavaVersion>
                <requireMavenVersion>
                  <version>${mdu.maven.version}</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
          <execution>
            <id>enforce-bytecode-version</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <enforceBytecodeVersion>
                  <maxJdkVersion>${maven.compiler.release}</maxJdkVersion>
                  <excludes>
                    <exclude>mysql:mysql-connector-java</exclude>
                  </excludes>
                  <ignoreClasses>
                    <!-- These 2 classes from com.sun.xml.bind:jaxb-impl contains Java 11 bytecode (55), but are in the directory for Java 9 bytecode (53) -->
                    <ignoreClass>META-INF/versions/9/com/sun/istack/logging/StackHelper</ignoreClass>
                    <ignoreClass>META-INF/versions/9/com/sun/xml/bind/StackHelper</ignoreClass>
                  </ignoreClasses>
                </enforceBytecodeVersion>
              </rules>
              <fail>true</fail>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>extra-enforcer-rules</artifactId>
            <version>${mdu.extra-enforcer-rules.version}</version>
          </dependency>
        </dependencies>
      </plugin>
      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <reporting>
    <excludeDefaults>true</excludeDefaults>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-project-info-reports-plugin</artifactId>
        <version>${mdu.maven-project-info-reports-plugin.version}</version>
        <reportSets>
          <reportSet>
            <reports>
              <report>index</report>
              <report>team</report>
            </reports>
          </reportSet>
        </reportSets>
      </plugin>
    </plugins>
  </reporting>

  <profiles>
    <profile>
      <!-- Validate the changes.xml file automatically, but only if it exists -->
      <id>changes-validate</id>
      <activation>
        <file>
          <exists>src/changes/changes.xml</exists>
        </file>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-changes-plugin</artifactId>
            <executions>
              <execution>
                <id>changes-validate</id>
                <phase>validate</phase>
                <goals>
                  <goal>changes-validate</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>changes</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-changes-plugin</artifactId>
            <executions>
              <execution>
                <id>changes-check</id>
                <phase>validate</phase>
                <goals>
                  <goal>changes-check</goal>
                </goals>
              </execution>
              <execution>
                <id>announcement-generate</id>
                <phase>verify</phase>
                <goals>
                  <goal>announcement-generate</goal>
                </goals>
              </execution>
            </executions>
          </plugin>

          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-releaselog</id>
                <phase>verify</phase>
                <goals>
                  <goal>attach-artifact</goal>
                </goals>
                <configuration>
                  <artifacts>
                    <artifact>
                      <classifier>releaselog</classifier>
                      <file>${project.build.directory}/announcement/announcement.vm</file>
                      <type>txt</type>
                    </artifact>
                  </artifacts>
                  <runOnlyAtExecutionRoot>true</runOnlyAtExecutionRoot>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>code-coverage</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jacoco-prepare-agent</id>
                <goals>
                  <goal>prepare-agent</goal>
                </goals>
              </execution>
              <execution>
                <id>jacoco-prepare-agent-integration</id>
                <goals>
                  <goal>prepare-agent-integration</goal>
                </goals>
              </execution>
              <execution>
                <id>jacoco-report</id>
                <goals>
                  <goal>report</goal>
                </goals>
              </execution>
              <execution>
                <id>jacoco-report-integration</id>
                <goals>
                  <goal>report-integration</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>installation</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-installation</id>
                <phase>verify</phase>
                <goals>
                  <goal>attach-artifact</goal>
                </goals>
                <configuration>
                  <artifacts>
                    <artifact>
                      <classifier>installation</classifier>
                      <file>installation.txt</file>
                      <type>txt</type>
                    </artifact>
                  </artifacts>
                  <runOnlyAtExecutionRoot>true</runOnlyAtExecutionRoot>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>maven-3</id>
      <activation>
        <file>
          <!--  This employs that the basedir expression is only recognized by Maven 3.x (see MNG-2363) -->
          <exists>${basedir}</exists>
        </file>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-site-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-descriptor</id>
                <goals>
                  <goal>attach-descriptor</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>mdh-release</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <executions>
              <execution>
                <id>sign-release-artifacts</id>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-javadocs</id>
                <goals>
                  <goal>jar</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-sources</id>
                <goals>
                  <goal>jar-no-fork</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <mdh.logging.email.level>error</mdh.logging.email.level>
        <mdh.logging.file.level>info</mdh.logging.file.level>
        <mdh.logging.product.level>info</mdh.logging.product.level>
      </properties>
    </profile>

    <profile>
      <id>toolchains</id>
      <!-- Activate this profile to use Toolchains -->
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-toolchains-plugin</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>toolchain</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
